# Generated by Django 4.2.6 on 2023-11-02 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carshop", "0002_remove_order_dealership"),
    ]

    operations = [
        migrations.AddField(
            model_name="licence",
            name="order",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car_licence",
                to="carshop.order",
            ),
            preserve_default=False,
        ),
    ]
