# Generated by Django 4.2.6 on 2023-12-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carshop", "0003_licence_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarPhotos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(blank=True, upload_to="image")),
            ],
        ),
    ]
