# Generated by Django 4.2.6 on 2023-12-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carshop", "0004_carphotos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carphotos",
            name="image",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
    ]
