# Generated by Django 4.2.6 on 2023-12-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carshop", "0005_alter_carphotos_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CarPhotos",
        ),
        migrations.AddField(
            model_name="cartype",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="Images_of_cars"),
        ),
    ]
