# Generated by Django 4.2.6 on 2024-01-10 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("carshop", "0007_carphotos"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_url",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orderquantity",
            name="car_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car_types",
                to="carshop.cartype",
            ),
        ),
        migrations.AlterField(
            model_name="orderquantity",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_quantities",
                to="carshop.order",
            ),
        ),
    ]
