# Generated by Django 4.2.6 on 2024-01-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "carshop",
            "0008_alter_car_options_order_invoice_url_order_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoice_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
