# Generated by Django 4.2.6 on 2024-01-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carshop", "0009_order_invoice_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonoSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_key", models.CharField(max_length=100, unique=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
